# Generated by ChatGPT on 2025-12-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_catalogs_and_list_catalog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passportstamp",
            name="last_checked_at",
        ),
    ]
