# Generated by ChatGPT on 2025-12-30

from django.db import migrations, models
from django.utils.text import slugify


def forwards_migrate_catalogs(apps, schema_editor):
    Catalog = apps.get_model("lists", "Catalog")
    VisitingList = apps.get_model("lists", "VisitingList")
    VisitingPlace = apps.get_model("lists", "VisitingPlace")
    PassportStamp = apps.get_model("lists", "PassportStamp")
    db_alias = schema_editor.connection.alias

    for visiting_list in VisitingList.objects.using(db_alias).select_related("catalog"):
        catalog = visiting_list.catalog
        if catalog is None:
            base_slug = slugify(visiting_list.name) or "catalog"
            slug = f"{base_slug}-{visiting_list.id}"
            catalog = Catalog.objects.using(db_alias).create(
                name=visiting_list.name,
                slug=slug,
                description=visiting_list.description,
                query=getattr(visiting_list, "query", "") or "",
                created_by=visiting_list.created_by,
            )
            visiting_list.catalog = catalog
            visiting_list.save(update_fields=["catalog"])
        else:
            if not getattr(catalog, "query", ""):
                catalog.query = getattr(visiting_list, "query", "") or ""
                catalog.save(update_fields=["query"])

    for place in VisitingPlace.objects.using(db_alias).select_related("visiting_list"):
        visiting_list = getattr(place, "visiting_list", None)
        if visiting_list and visiting_list.catalog_id:
            place.catalog_id = visiting_list.catalog_id
            place.save(update_fields=["catalog"])

    for catalog in Catalog.objects.using(db_alias).all():
        seen = {}
        for place in (
            VisitingPlace.objects.using(db_alias)
            .filter(catalog_id=catalog.id)
            .order_by("id")
        ):
            if place.entity_id not in seen:
                seen[place.entity_id] = place
                continue
            primary = seen[place.entity_id]
            for stamp in PassportStamp.objects.using(db_alias).filter(place_id=place.id):
                exists = PassportStamp.objects.using(db_alias).filter(
                    user_id=stamp.user_id, place_id=primary.id
                ).exists()
                if exists:
                    stamp.delete()
                else:
                    stamp.place_id = primary.id
                    stamp.save(update_fields=["place"])
            place.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_remove_passportstamp_last_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="query",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visitingplace",
            name="catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="places",
                to="lists.catalog",
            ),
        ),
        migrations.RunPython(forwards_migrate_catalogs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="visitinglist",
            name="catalog",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="lists",
                to="lists.catalog",
            ),
        ),
        migrations.RemoveField(
            model_name="visitinglist",
            name="query",
        ),
        migrations.AlterUniqueTogether(
            name="visitingplace",
            unique_together={("catalog", "entity_id")},
        ),
        migrations.RemoveField(
            model_name="visitingplace",
            name="visiting_list",
        ),
        migrations.AlterField(
            model_name="visitingplace",
            name="catalog",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="places",
                to="lists.catalog",
            ),
        ),
    ]
