# Generated by Django 5.2.9 on 2025-12-30 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_catalog_query_and_personal_lists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitinglist',
            unique_together={('catalog', 'created_by')},
        ),
        migrations.AddField(
            model_name='visitingplace',
            name='coord',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='visitinglist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='visitinglist',
            name='name',
        ),
    ]
